config/routes.rb
Rails.application.routes.draw do
  resources :edificis
  resources :ites
  resources :deficiencies
  devise_for :users
  get 'home/index'
  get 'home/contacta'

  root :to => "home#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/deficiencia.rb
class Deficiencia < ApplicationRecord
end

app/models/edifici.rb
class Edifici < ApplicationRecord
end

app/models/ite.rb
class Ite < ApplicationRecord

	has_attached_file :itexml
	validates_attachment_content_type :itexml, content_type: "text/xml"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/deficiencies_controller.rb
class DeficienciesController < ApplicationController
  before_action :set_deficiencia, only: [:show, :edit, :update, :destroy]

  # GET /deficiencies
  # GET /deficiencies.json
  def index
    @deficiencies = Deficiencia.all
  end

  # GET /deficiencies/1
  # GET /deficiencies/1.json
  def show
  end

  # GET /deficiencies/new
  def new
    @deficiencia = Deficiencia.new
  end

  # GET /deficiencies/1/edit
  def edit
  end

  # POST /deficiencies
  # POST /deficiencies.json
  def create
    @deficiencia = Deficiencia.new(deficiencia_params)

    respond_to do |format|
      if @deficiencia.save
        format.html { redirect_to @deficiencia, notice: 'Deficiencia was successfully created.' }
        format.json { render :show, status: :created, location: @deficiencia }
      else
        format.html { render :new }
        format.json { render json: @deficiencia.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deficiencies/1
  # PATCH/PUT /deficiencies/1.json
  def update
    respond_to do |format|
      if @deficiencia.update(deficiencia_params)
        format.html { redirect_to @deficiencia, notice: 'Deficiencia was successfully updated.' }
        format.json { render :show, status: :ok, location: @deficiencia }
      else
        format.html { render :edit }
        format.json { render json: @deficiencia.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deficiencies/1
  # DELETE /deficiencies/1.json
  def destroy
    @deficiencia.destroy
    respond_to do |format|
      format.html { redirect_to deficiencies_url, notice: 'Deficiencia was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deficiencia
      @deficiencia = Deficiencia.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def deficiencia_params
      params.require(:deficiencia).permit(:edifici_id, :descripcio, :sistema, :qualificacio)
    end
end

app/controllers/edificis_controller.rb
class EdificisController < ApplicationController
  before_action :set_edifici, only: [:show, :edit, :update, :destroy]

  # GET /edificis
  # GET /edificis.json
  def index
    @edificis = Edifici.all
  end

  # GET /edificis/1
  # GET /edificis/1.json
  def show
  end

  # GET /edificis/new
  def new
    @edifici = Edifici.new
  end

  # GET /edificis/1/edit
  def edit
  end

  # POST /edificis
  # POST /edificis.json
  def create
    @edifici = Edifici.new(edifici_params)

    respond_to do |format|
      if @edifici.save
        format.html { redirect_to @edifici, notice: 'Edifici was successfully created.' }
        format.json { render :show, status: :created, location: @edifici }
      else
        format.html { render :new }
        format.json { render json: @edifici.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /edificis/1
  # PATCH/PUT /edificis/1.json
  def update
    respond_to do |format|
      if @edifici.update(edifici_params)
        format.html { redirect_to @edifici, notice: 'Edifici was successfully updated.' }
        format.json { render :show, status: :ok, location: @edifici }
      else
        format.html { render :edit }
        format.json { render json: @edifici.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /edificis/1
  # DELETE /edificis/1.json
  def destroy
    @edifici.destroy
    respond_to do |format|
      format.html { redirect_to edificis_url, notice: 'Edifici was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_edifici
      @edifici = Edifici.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def edifici_params
      params.require(:edifici).permit(:user_id, :nom_edifici, :tipus_edifici)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/ites_controller.rb
class ItesController < ApplicationController
  before_action :set_ite, only: [:show, :edit, :update, :destroy]

  # GET /ites
  # GET /ites.json
  def index
    @ites = Ite.all
  end

  # GET /ites/1
  # GET /ites/1.json
  def show
    ite = Ite.find(params[:id])
    @doc = Nokogiri::XML(open(ite.itexml.url))
    @url_ite = ite.itexml.url
    @missatge = @doc.xpath('//Municipio').text
  end

  # GET /ites/new
  def new
    @ite = Ite.new
  end

  # GET /ites/1/edit
  def edit
  end

  # POST /ites
  # POST /ites.json
  def create
    @ite = Ite.new(ite_params)

    respond_to do |format|
      if @ite.save
        format.html { redirect_to @ite, notice: 'Ite was successfully created.' }
        format.json { render :show, status: :created, location: @ite }
      else
        format.html { render :new }
        format.json { render json: @ite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ites/1
  # PATCH/PUT /ites/1.json
  def update
    respond_to do |format|
      if @ite.update(ite_params)
        format.html { redirect_to @ite, notice: 'Ite was successfully updated.' }
        format.json { render :show, status: :ok, location: @ite }
      else
        format.html { render :edit }
        format.json { render json: @ite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ites/1
  # DELETE /ites/1.json
  def destroy
    @ite.destroy
    respond_to do |format|
      format.html { redirect_to ites_url, notice: 'Ite was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ite
      @ite = Ite.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ite_params
      params.require(:ite).permit(:edifici_id, :existeix, :itexml)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deficiencies_helper.rb
module DeficienciesHelper
end

app/helpers/edificis_helper.rb
module EdificisHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ites_helper.rb
module ItesHelper
end

app/views/deficiencies/_form.html.erb
<%= simple_form_for(@deficiencia) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :edifici_id %>
    <%= f.input :descripcio %>
    <%= f.input :sistema %>
    <%= f.input :qualificacio %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/deficiencies/edit.html.erb
<h1>Editing Deficiencia</h1>

<%= render 'form', deficiencia: @deficiencia %>

<%= link_to 'Show', @deficiencia %> |
<%= link_to 'Back', deficiencies_path %>

app/views/deficiencies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Deficiencies</h1>

<table>
  <thead>
    <tr>
      <th>Edifici</th>
      <th>Descripcio</th>
      <th>Sistema</th>
      <th>Qualificacio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @deficiencies.each do |deficiencia| %>
      <tr>
        <td><%= deficiencia.edifici_id %></td>
        <td><%= deficiencia.descripcio %></td>
        <td><%= deficiencia.sistema %></td>
        <td><%= deficiencia.qualificacio %></td>
        <td><%= link_to 'Show', deficiencia %></td>
        <td><%= link_to 'Edit', edit_deficiencia_path(deficiencia) %></td>
        <td><%= link_to 'Destroy', deficiencia, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Deficiencia', new_deficiencia_path %>

app/views/deficiencies/new.html.erb
<h1>New Deficiencia</h1>

<%= render 'form', deficiencia: @deficiencia %>

<%= link_to 'Back', deficiencies_path %>

app/views/deficiencies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Edifici:</strong>
  <%= @deficiencia.edifici_id %>
</p>

<p>
  <strong>Descripcio:</strong>
  <%= @deficiencia.descripcio %>
</p>

<p>
  <strong>Sistema:</strong>
  <%= @deficiencia.sistema %>
</p>

<p>
  <strong>Qualificacio:</strong>
  <%= @deficiencia.qualificacio %>
</p>

<%= link_to 'Edit', edit_deficiencia_path(@deficiencia) %> |
<%= link_to 'Back', deficiencies_path %>

app/views/edificis/_form.html.erb
<%= simple_form_for(@edifici) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :user_id %>
    <%= f.input :nom_edifici %>
    <%= f.input :tipus_edifici %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/edificis/edit.html.erb
<h1>Editing Edifici</h1>

<%= render 'form', edifici: @edifici %>

<%= link_to 'Show', @edifici %> |
<%= link_to 'Back', edificis_path %>

app/views/edificis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Edificis</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Nom edifici</th>
      <th>Tipus edifici</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @edificis.each do |edifici| %>
      <tr>
        <td><%= edifici.user_id %></td>
        <td><%= edifici.nom_edifici %></td>
        <td><%= edifici.tipus_edifici %></td>
        <td><%= link_to 'Show', edifici %></td>
        <td><%= link_to 'Edit', edit_edifici_path(edifici) %></td>
        <td><%= link_to 'Destroy', edifici, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Edifici', new_edifici_path %>

app/views/edificis/new.html.erb
<h1>New Edifici</h1>

<%= render 'form', edifici: @edifici %>

<%= link_to 'Back', edificis_path %>

app/views/edificis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @edifici.user_id %>
</p>

<p>
  <strong>Nom edifici:</strong>
  <%= @edifici.nom_edifici %>
</p>

<p>
  <strong>Tipus edifici:</strong>
  <%= @edifici.tipus_edifici %>
</p>

<%= link_to 'Edit', edit_edifici_path(@edifici) %> |
<%= link_to 'Back', edificis_path %>

app/views/home/contacta.html.erb
<div class="background-seccio">
	<div class="row">
		<div class="large-12 columns">
			<div class="titol-seccio">
				<%= t('.titol_contacta') %>
			</div>
		</div>
	</div>
	
	<div class="row">
		<div class="medium-12 columns">
			<div class="container-info">
				<p><%= t('.text_contacta') %><br/>
				assessoriatecnica@apabcn.cat</p>
			</div>
		</div>
	</div>
</div>

app/views/home/index.html.erb
<h1>Tècnic de capçalera</h1>

app/views/ites/_form.html.erb
<%= simple_form_for @ite, url: ites_path do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :edifici_id %>
    <%= f.input :existeix %>
    <%= f.input :itexml, as: :file %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/ites/edit.html.erb
<h1>Editing Ite</h1>

<%= render 'form', ite: @ite %>

<%= link_to 'Show', @ite %> |
<%= link_to 'Back', ites_path %>

app/views/ites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ites</h1>

<table>
  <thead>
    <tr>
      <th>Edifici</th>
      <th>Existeix</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ites.each do |ite| %>
      <tr>
        <td><%= ite.edifici_id %></td>
        <td><%= ite.existeix %></td>
        <td><%= link_to 'Show', ite %></td>
        <td><%= link_to 'Edit', edit_ite_path(ite) %></td>
        <td><%= link_to 'Destroy', ite, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ite', new_ite_path %>

app/views/ites/new.html.erb
<h1>New Ite</h1>

<%= render 'form', ite: @ite %>

<%= link_to 'Back', ites_path %>

app/views/ites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Edifici:</strong>
  <%= @ite.edifici_id %>
</p>

<p>
  <strong>Existeix:</strong>
  <%= @ite.existeix %>
</p>

<p>URL: <%= @url_ite %></p>
<p>Missatge: <%= @missatge %></p>


<%= link_to 'Edit', edit_ite_path(@ite) %> |
<%= link_to 'Back', ites_path %>

app/views/layouts/_footer.html.erb
		<footer>
			<div class="footer-container">
				<div class="row">
					<div class="medium-12 columns">
						<div class="footer-text-container">
							<%= image_tag('logo_caateeb.png', :alt => t('.logo_caateeb'), :class => 'logo-caateeb') %>
							<br/>
							© <%= Time.now.year %> CAATEEB - <a href="http://www.apabcn.cat/ca_es/altres/Pagines/avislegal.aspx"><%= t('.avis_legal') %></a> - <%= link_to t('.contacta'), home_contacta_path %>
						</div>
					</div>
				</div>
			</div>
    </footer>
  </body>
</html>

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html lang="ca">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Tècnic de capçalera" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

 	<body>
		<div class="top-bar">
		  <div class="top-bar-title">
		    <span data-responsive-toggle="responsive-menu" data-hide-for="medium">
		      <button class="menu-icon dark" type="button" data-toggle></button>
		    </span>
		    <strong>Tècnic de capçalera</strong>
		  </div>
		  <div id="responsive-menu">
		    <div class="top-bar-left">
		      
		    </div>
		    <div class="top-bar-right">
		      <ul class="dropdown menu" data-dropdown-menu>
		        <li><a href="#">Projectes</a></li>
		        <li><a href="#">jordimarti@me.com</a></li>
		      </ul>
		    </div>
		  </div>
		</div>

app/views/layouts/application.html.erb
<%= render 'layouts/header' %>
    <main role="main">
      <%= yield %>
    </main>
    
<%= render 'layouts/footer' %>